# Tensor Inner Product and Outer Product

This tutorial explores two fundamental tensor operations: the **inner product** (dot product) and the **outer product**. These operations are essential in linear algebra, quantum computing, machine learning, and scientific computing.

## 1. Setup

First, let's import NumPy.

In [1]:
import numpy as np

## 2. Inner Product (Dot Product)

The **inner product** (also called dot product) of two vectors produces a **scalar**.

### Definition

For vectors $\mathbf{u} = [u_1, u_2, \ldots, u_n]$ and $\mathbf{v} = [v_1, v_2, \ldots, v_n]$:

$$\mathbf{u} \cdot \mathbf{v} = \sum_{i=1}^{n} u_i v_i = u_1 v_1 + u_2 v_2 + \cdots + u_n v_n$$

This measures the **projection** of one vector onto another and captures their **similarity**.

### 2.1 Vector Inner Product

In [2]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Method 1: np.dot()
result1 = np.dot(u, v)

# Method 2: @ operator
result2 = u @ v

# Method 3: np.inner()
result3 = np.inner(u, v)

print(f"u = {u}")
print(f"v = {v}")
print(f"\nu · v = {result1}")
print(f"\nAll methods equal: {result1 == result2 == result3}")

u = [1 2 3]
v = [4 5 6]

u · v = 32

All methods equal: True


### Manual Calculation

In [3]:
manual = u[0]*v[0] + u[1]*v[1] + u[2]*v[2]
print(f"Manual: {u[0]}*{v[0]} + {u[1]}*{v[1]} + {u[2]}*{v[2]} = {manual}")
print(f"NumPy:  {result1}")
print(f"Match:  {manual == result1}")

Manual: 1*4 + 2*5 + 3*6 = 32
NumPy:  32
Match:  True


### 2.2 Geometric Interpretation

The inner product relates to the **angle** between vectors:

$$\mathbf{u} \cdot \mathbf{v} = \|\mathbf{u}\| \|\mathbf{v}\| \cos(\theta)$$

where $\theta$ is the angle between the vectors.

In [4]:
# Calculate angle between vectors
dot_product = np.dot(u, v)
magnitude_u = np.linalg.norm(u)
magnitude_v = np.linalg.norm(v)

cos_theta = dot_product / (magnitude_u * magnitude_v)
theta_radians = np.arccos(cos_theta)
theta_degrees = np.degrees(theta_radians)

print(f"||u|| = {magnitude_u:.4f}")
print(f"||v|| = {magnitude_v:.4f}")
print(f"cos(θ) = {cos_theta:.4f}")
print(f"θ = {theta_degrees:.2f}°")

||u|| = 3.7417
||v|| = 8.7750
cos(θ) = 0.9746
θ = 12.93°


### 2.3 Special Cases

- **Orthogonal vectors**: $\mathbf{u} \cdot \mathbf{v} = 0$ (perpendicular, $\theta = 90°$)
- **Parallel vectors**: $|\mathbf{u} \cdot \mathbf{v}| = \|\mathbf{u}\| \|\mathbf{v}\|$ ($\theta = 0°$ or $180°$)

In [5]:
# Orthogonal vectors
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print(f"Orthogonal vectors: {a} · {b} = {np.dot(a, b)}")

# Parallel vectors
c = np.array([2, 4, 6])
d = np.array([1, 2, 3])
print(f"\nParallel vectors: {c} · {d} = {np.dot(c, d)}")
print(f"||c|| * ||d|| = {np.linalg.norm(c) * np.linalg.norm(d):.4f}")

Orthogonal vectors: [1 0 0] · [0 1 0] = 0

Parallel vectors: [2 4 6] · [1 2 3] = 28
||c|| * ||d|| = 28.0000


### 2.4 Properties of Inner Product

1. **Commutativity**: $\mathbf{u} \cdot \mathbf{v} = \mathbf{v} \cdot \mathbf{u}$
2. **Distributivity**: $\mathbf{u} \cdot (\mathbf{v} + \mathbf{w}) = \mathbf{u} \cdot \mathbf{v} + \mathbf{u} \cdot \mathbf{w}$
3. **Scalar multiplication**: $(k\mathbf{u}) \cdot \mathbf{v} = k(\mathbf{u} \cdot \mathbf{v})$
4. **Positive definite**: $\mathbf{u} \cdot \mathbf{u} \geq 0$, and equals zero only if $\mathbf{u} = \mathbf{0}$

In [6]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
w = np.array([7, 8, 9])
k = 3

# Commutativity
print(f"Commutative: u·v = {np.dot(u, v)}, v·u = {np.dot(v, u)}")

# Distributivity
left = np.dot(u, v + w)
right = np.dot(u, v) + np.dot(u, w)
print(f"\nDistributive: u·(v+w) = {left}, u·v + u·w = {right}")

# Scalar multiplication
print(f"\nScalar: (k*u)·v = {np.dot(k*u, v)}, k*(u·v) = {k * np.dot(u, v)}")

# Positive definite
print(f"\nPositive definite: u·u = {np.dot(u, u)} ≥ 0")

Commutative: u·v = 32, v·u = 32

Distributive: u·(v+w) = 82, u·v + u·w = 82

Scalar: (k*u)·v = 96, k*(u·v) = 96

Positive definite: u·u = 14 ≥ 0


### 2.5 Matrix-Vector Inner Product

When computing the inner product between a matrix and vector, the result is a vector.

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
x = np.array([1, 0, 1])

result = A @ x
print(f"Matrix A:\n{A}")
print(f"\nVector x: {x}")
print(f"\nA @ x = {result}")
print(f"\nEach element is the inner product of a row of A with x:")
print(f"Row 0: {A[0]} · {x} = {np.dot(A[0], x)}")
print(f"Row 1: {A[1]} · {x} = {np.dot(A[1], x)}")

Matrix A:
[[1 2 3]
 [4 5 6]]

Vector x: [1 0 1]

A @ x = [ 4 10]

Each element is the inner product of a row of A with x:
Row 0: [1 2 3] · [1 0 1] = 4
Row 1: [4 5 6] · [1 0 1] = 10


## 3. Outer Product

The **outer product** of two vectors produces a **matrix**.

### Definition

For vectors $\mathbf{u} = [u_1, u_2, \ldots, u_m]$ and $\mathbf{v} = [v_1, v_2, \ldots, v_n]$:

$$\mathbf{u} \otimes \mathbf{v} = \mathbf{u} \mathbf{v}^T = \begin{bmatrix}
u_1 v_1 & u_1 v_2 & \cdots & u_1 v_n \\
u_2 v_1 & u_2 v_2 & \cdots & u_2 v_n \\
\vdots & \vdots & \ddots & \vdots \\
u_m v_1 & u_m v_2 & \cdots & u_m v_n
\end{bmatrix}$$

The result is an $m \times n$ matrix where element $(i,j)$ is $u_i \cdot v_j$.

### 3.1 Vector Outer Product

In [8]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6, 7])

# Method 1: np.outer()
result1 = np.outer(u, v)

# Method 2: reshape and use @ or matrix multiplication
result2 = u[:, np.newaxis] @ v[np.newaxis, :]

# Method 3: using reshape
result3 = u.reshape(-1, 1) @ v.reshape(1, -1)

print(f"u = {u} (shape {u.shape})")
print(f"v = {v} (shape {v.shape})")
print(f"\nu ⊗ v = \n{result1}")
print(f"Shape: {result1.shape}")
print(f"\nAll methods equal: {np.array_equal(result1, result2) and np.array_equal(result2, result3)}")

u = [1 2 3] (shape (3,))
v = [4 5 6 7] (shape (4,))

u ⊗ v = 
[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]
Shape: (3, 4)

All methods equal: True


### Manual Calculation

In [9]:
print("Manual outer product calculation:")
print(f"Element [0,0]: u[0] * v[0] = {u[0]} * {v[0]} = {u[0] * v[0]}")
print(f"Element [0,1]: u[0] * v[1] = {u[0]} * {v[1]} = {u[0] * v[1]}")
print(f"Element [1,0]: u[1] * v[0] = {u[1]} * {v[0]} = {u[1] * v[0]}")
print(f"Element [2,3]: u[2] * v[3] = {u[2]} * {v[3]} = {u[2] * v[3]}")
print(f"\nNumPy result[2,3] = {result1[2, 3]}")

Manual outer product calculation:
Element [0,0]: u[0] * v[0] = 1 * 4 = 4
Element [0,1]: u[0] * v[1] = 1 * 5 = 5
Element [1,0]: u[1] * v[0] = 2 * 4 = 8
Element [2,3]: u[2] * v[3] = 3 * 7 = 21

NumPy result[2,3] = 21


### 3.2 Rank-1 Matrix

The outer product always produces a **rank-1 matrix** (all rows are scalar multiples of each other).

In [10]:
a = np.array([2, 3])
b = np.array([5, 7, 9])

M = np.outer(a, b)
print(f"M = a ⊗ b =\n{M}")
print(f"\nRank of M: {np.linalg.matrix_rank(M)}")
print("\nNotice that row 1 = (3/2) * row 0:")
print(f"Row 0: {M[0]}")
print(f"Row 1: {M[1]}")
print(f"(3/2) * Row 0 = {(3/2) * M[0]}")

M = a ⊗ b =
[[10 14 18]
 [15 21 27]]

Rank of M: 1

Notice that row 1 = (3/2) * row 0:
Row 0: [10 14 18]
Row 1: [15 21 27]
(3/2) * Row 0 = [15. 21. 27.]


### 3.3 Properties of Outer Product

1. **Non-commutative**: $\mathbf{u} \otimes \mathbf{v} \neq \mathbf{v} \otimes \mathbf{u}$ (different shapes, unless both are same length)
2. **Bilinearity**: $(k\mathbf{u}) \otimes \mathbf{v} = \mathbf{u} \otimes (k\mathbf{v}) = k(\mathbf{u} \otimes \mathbf{v})$
3. **Distributivity**: $\mathbf{u} \otimes (\mathbf{v} + \mathbf{w}) = \mathbf{u} \otimes \mathbf{v} + \mathbf{u} \otimes \mathbf{w}$

In [11]:
u = np.array([1, 2])
v = np.array([3, 4])
w = np.array([5, 6])
k = 2

# Non-commutative (when same shape, transposes of each other)
uv = np.outer(u, v)
vu = np.outer(v, u)
print("u ⊗ v =")
print(uv)
print("\nv ⊗ u =")
print(vu)
print(f"\n(u ⊗ v)^T = (v ⊗ u)? {np.array_equal(uv.T, vu)}")

# Bilinearity
print(f"\nBilinearity: (k*u) ⊗ v = u ⊗ (k*v) = k*(u ⊗ v)?")
left = np.outer(k*u, v)
middle = np.outer(u, k*v)
right = k * np.outer(u, v)
print(np.array_equal(left, middle) and np.array_equal(middle, right))

# Distributivity
print(f"\nDistributivity: u ⊗ (v+w) = u⊗v + u⊗w?")
left = np.outer(u, v + w)
right = np.outer(u, v) + np.outer(u, w)
print(np.array_equal(left, right))

u ⊗ v =
[[3 4]
 [6 8]]

v ⊗ u =
[[3 6]
 [4 8]]

(u ⊗ v)^T = (v ⊗ u)? True

Bilinearity: (k*u) ⊗ v = u ⊗ (k*v) = k*(u ⊗ v)?
True

Distributivity: u ⊗ (v+w) = u⊗v + u⊗w?
True


## 4. Comparing Inner and Outer Products

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner = np.inner(a, b)
outer = np.outer(a, b)

print("=" * 50)
print("INNER PRODUCT vs OUTER PRODUCT")
print("=" * 50)

print(f"\nVectors: a = {a}, b = {b}")

print(f"\nInner product (a · b):")
print(f"  Result: {inner}")
print(f"  Type: scalar")
print(f"  Interpretation: measures similarity/projection")

print(f"\nOuter product (a ⊗ b):")
print(f"  Result:\n{outer}")
print(f"  Shape: {outer.shape}")
print(f"  Type: matrix (rank-1)")
print(f"  Interpretation: generates all pairwise products")

INNER PRODUCT vs OUTER PRODUCT

Vectors: a = [1 2 3], b = [4 5 6]

Inner product (a · b):
  Result: 32
  Type: scalar
  Interpretation: measures similarity/projection

Outer product (a ⊗ b):
  Result:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
  Shape: (3, 3)
  Type: matrix (rank-1)
  Interpretation: generates all pairwise products


## 5. Applications

### 5.1 Inner Product: Cosine Similarity

Used in NLP, recommendation systems, and clustering to measure document/vector similarity.

In [13]:
# Two document vectors (e.g., word counts)
doc1 = np.array([3, 2, 0, 5])  # "cat", "dog", "bird", "fish"
doc2 = np.array([2, 3, 0, 4])

# Cosine similarity
cosine_sim = np.dot(doc1, doc2) / (np.linalg.norm(doc1) * np.linalg.norm(doc2))
print(f"Document 1: {doc1}")
print(f"Document 2: {doc2}")
print(f"Cosine similarity: {cosine_sim:.4f}")
print(f"\nInterpretation: similarity ranges from -1 (opposite) to 1 (identical)")
print(f"These documents are highly similar ({cosine_sim:.2%})")

Document 1: [3 2 0 5]
Document 2: [2 3 0 4]
Cosine similarity: 0.9640

Interpretation: similarity ranges from -1 (opposite) to 1 (identical)
These documents are highly similar (96.40%)


### 5.2 Outer Product: Rank-1 Updates

Used in machine learning (gradient descent), quantum computing (density matrices), and linear algebra.

In [14]:
# Rank-1 update: A_new = A_old + α * u ⊗ v
A = np.array([[1, 2],
              [3, 4]])
u = np.array([1, 1])
v = np.array([2, 3])
alpha = 0.5

A_new = A + alpha * np.outer(u, v)

print(f"Original matrix A:\n{A}")
print(f"\nRank-1 update: α * (u ⊗ v) =\n{alpha * np.outer(u, v)}")
print(f"\nUpdated matrix A_new:\n{A_new}")

Original matrix A:
[[1 2]
 [3 4]]

Rank-1 update: α * (u ⊗ v) =
[[1.  1.5]
 [1.  1.5]]

Updated matrix A_new:
[[2.  3.5]
 [4.  5.5]]


### 5.3 Quantum Computing: Tensor Products

In quantum computing, the outer product (tensor product) combines quantum states.

In [15]:
# Quantum states (normalized vectors)
psi = np.array([1, 0])  # |0⟩ state
phi = np.array([1/np.sqrt(2), 1/np.sqrt(2)])  # |+⟩ state (superposition)

# Tensor product creates a 2-qubit state
psi_phi = np.kron(psi, phi)  # kron is generalized outer product for tensors

print(f"State |ψ⟩ = {psi}")
print(f"State |φ⟩ = {phi}")
print(f"\nTensor product |ψ⟩ ⊗ |φ⟩ = {psi_phi}")
print(f"\nThis represents a 2-qubit system in state |0+⟩")

State |ψ⟩ = [1 0]
State |φ⟩ = [0.70710678 0.70710678]

Tensor product |ψ⟩ ⊗ |φ⟩ = [0.70710678 0.70710678 0.         0.        ]

This represents a 2-qubit system in state |0+⟩


## 6. Higher-Dimensional Tensors

NumPy's `np.tensordot()` and `np.einsum()` generalize these operations to higher dimensions.

In [16]:
# 3D tensors
T1 = np.random.rand(2, 3, 4)
T2 = np.random.rand(4, 5)

# Contract over the last axis of T1 and first axis of T2
result = np.tensordot(T1, T2, axes=([2], [0]))

print(f"T1 shape: {T1.shape}")
print(f"T2 shape: {T2.shape}")
print(f"Result shape: {result.shape}")
print(f"\nContraction over axis 2 of T1 and axis 0 of T2")
print(f"Result has shape (2, 3, 5)")

T1 shape: (2, 3, 4)
T2 shape: (4, 5)
Result shape: (2, 3, 5)

Contraction over axis 2 of T1 and axis 0 of T2
Result has shape (2, 3, 5)


## 7. Summary Table

| Property | Inner Product | Outer Product |
|----------|---------------|---------------|
| **Notation** | $\mathbf{u} \cdot \mathbf{v}$ or $\langle \mathbf{u}, \mathbf{v} \rangle$ | $\mathbf{u} \otimes \mathbf{v}$ or $\mathbf{u} \mathbf{v}^T$ |
| **Input** | Two vectors of same length | Two vectors (any lengths) |
| **Output** | Scalar | Matrix |
| **Dimensions** | $(n,) \times (n,) \rightarrow ()$ | $(m,) \times (n,) \rightarrow (m, n)$ |
| **NumPy** | `np.dot()`, `@`, `np.inner()` | `np.outer()` |
| **Commutativity** | Yes | No (transpose) |
| **Interpretation** | Similarity, projection | All pairwise products |
| **Rank** | N/A | Always 1 |

## 8. Exercises

1. Compute the inner and outer products of $\mathbf{u} = [1, -1, 2]$ and $\mathbf{v} = [3, 0, 1]$. Verify the outer product has rank 1.

2. Given two vectors representing RGB color values, use the inner product to determine if they are orthogonal.

3. Create a $4 \times 4$ matrix using the outer product of $\mathbf{a} = [1, 2, 3, 4]$ with itself. What pattern do you notice?

4. For quantum computing: compute the tensor product of two Bell state vectors and verify the result is normalized.

In [17]:
# Your code here
