# Matrix Addition with NumPy

This tutorial covers the fundamentals of matrix addition using NumPy. You'll learn how to add matrices, understand the rules that govern the operation, and explore related concepts like scalar addition and broadcasting.

## 1. Setup

First, let's import NumPy.

In [1]:
import numpy as np

## 2. Creating Matrices

Let's create a few matrices to work with throughout the tutorial.

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

print("Matrix A (2x3):")
print(A)
print(f"Shape: {A.shape}\n")

print("Matrix B (2x3):")
print(B)
print(f"Shape: {B.shape}")

Matrix A (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Matrix B (2x3):
[[ 7  8  9]
 [10 11 12]]
Shape: (2, 3)


## 3. Matrix Addition Basics

Matrix addition is performed **element-wise**. Both matrices must have the **same shape**.

If $A$ and $B$ are both $(m \times n)$ matrices, the result $C = A + B$ is:

$$C_{ij} = A_{ij} + B_{ij}$$

In [3]:
# Method 1: the + operator
C1 = A + B

# Method 2: np.add()
C2 = np.add(A, B)

print("A + B =")
print(C1)
print(f"Result shape: {C1.shape}\n")

print("Both methods equal:", np.array_equal(C1, C2))

A + B =
[[ 8 10 12]
 [14 16 18]]
Result shape: (2, 3)

Both methods equal: True


### Manual Verification

Let's verify by checking a single element.

In [4]:
row, col = 1, 2
manual = A[row, col] + B[row, col]
print(f"Manual C[{row},{col}]: {A[row,col]} + {B[row,col]} = {manual}")
print(f"NumPy  C[{row},{col}]: {C1[row, col]}")
print(f"Match: {manual == C1[row, col]}")

Manual C[1,2]: 6 + 12 = 18
NumPy  C[1,2]: 18
Match: True


## 4. Matrix Subtraction

Subtraction works the same way - element-wise, requiring matching shapes.

In [5]:
D = A - B

print("A - B =")
print(D)

# Equivalent to adding the negation
print("\nA + (-B) =")
print(A + (-B))

print(f"\nSame result? {np.array_equal(D, A + (-B))}")

A - B =
[[-6 -6 -6]
 [-6 -6 -6]]

A + (-B) =
[[-6 -6 -6]
 [-6 -6 -6]]

Same result? True


## 5. Properties of Matrix Addition

### 5.1 Commutativity

Unlike matrix multiplication, addition **is** commutative: $A + B = B + A$.

In [6]:
print("A + B =")
print(A + B)

print("\nB + A =")
print(B + A)

print(f"\nCommutative? {np.array_equal(A + B, B + A)}")

A + B =
[[ 8 10 12]
 [14 16 18]]

B + A =
[[ 8 10 12]
 [14 16 18]]

Commutative? True


### 5.2 Associativity

$(A + B) + C = A + (B + C)$

In [7]:
E = np.array([[2, 4, 6],
              [8, 10, 12]])

left = (A + B) + E
right = A + (B + E)

print("(A + B) + E =")
print(left)

print("\nA + (B + E) =")
print(right)

print(f"\nAssociative? {np.array_equal(left, right)}")

(A + B) + E =
[[10 14 18]
 [22 26 30]]

A + (B + E) =
[[10 14 18]
 [22 26 30]]

Associative? True


### 5.3 Additive Identity (Zero Matrix)

Adding the zero matrix leaves the original unchanged: $A + 0 = A$.

In [8]:
Z = np.zeros_like(A)
print("Zero matrix:")
print(Z)

print("\nA + Z =")
print(A + Z)

print(f"\nA + Z == A? {np.array_equal(A + Z, A)}")

Zero matrix:
[[0 0 0]
 [0 0 0]]

A + Z =
[[1 2 3]
 [4 5 6]]

A + Z == A? True


### 5.4 Additive Inverse

Every matrix has an additive inverse: $A + (-A) = 0$.

In [9]:
print("A =")
print(A)

print("\n-A =")
print(-A)

print("\nA + (-A) =")
print(A + (-A))

print(f"\nAll zeros? {np.all(A + (-A) == 0)}")

A =
[[1 2 3]
 [4 5 6]]

-A =
[[-1 -2 -3]
 [-4 -5 -6]]

A + (-A) =
[[0 0 0]
 [0 0 0]]

All zeros? True


## 6. Scalar Addition

Adding a scalar to a matrix adds it to every element. This uses NumPy's broadcasting.

In [10]:
scalar = 10

print(f"A + {scalar} =")
print(A + scalar)

print(f"\nA - {scalar} =")
print(A - scalar)

A + 10 =
[[11 12 13]
 [14 15 16]]

A - 10 =
[[-9 -8 -7]
 [-6 -5 -4]]


## 7. Broadcasting in Addition

NumPy can add arrays of different shapes when they are **broadcast-compatible**. Broadcasting automatically expands the smaller array to match the larger one.

Common cases:
- Adding a row vector to every row of a matrix
- Adding a column vector to every column of a matrix

In [11]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Add a row vector to every row
row_vec = np.array([10, 20, 30])
print("Matrix M:")
print(M)
print(f"\nRow vector: {row_vec}")
print(f"\nM + row_vec (broadcast across rows):")
print(M + row_vec)

Matrix M:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row vector: [10 20 30]

M + row_vec (broadcast across rows):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [12]:
# Add a column vector to every column
col_vec = np.array([[100],
                    [200],
                    [300]])

print(f"Column vector:\n{col_vec}")
print(f"\nM + col_vec (broadcast across columns):")
print(M + col_vec)

Column vector:
[[100]
 [200]
 [300]]

M + col_vec (broadcast across columns):
[[101 102 103]
 [204 205 206]
 [307 308 309]]


## 8. In-place Addition

Use `+=` or `np.add()` with the `out` parameter to modify a matrix in-place, avoiding extra memory allocation.

In [13]:
X = np.array([[1, 2],
              [3, 4]])

Y = np.array([[5, 6],
              [7, 8]])

print(f"X before: id={id(X)}")
print(X)

X += Y

print(f"\nX after += Y: id={id(X)}")
print(X)
print("\nSame object in memory (in-place update).")

X before: id=4761037936
[[1 2]
 [3 4]]

X after += Y: id=4761037936
[[ 6  8]
 [10 12]]

Same object in memory (in-place update).


## 9. Common Pitfalls

### Shape Mismatch

If shapes are incompatible and can't be broadcast, you'll get a `ValueError`.

In [14]:
A_2x3 = np.array([[1, 2, 3],
                   [4, 5, 6]])    # shape (2, 3)

B_3x3 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])    # shape (3, 3)

try:
    result = A_2x3 + B_3x3
except ValueError as e:
    print(f"Error: {e}")
    print(f"Cannot add shapes {A_2x3.shape} and {B_3x3.shape}")

Error: operands could not be broadcast together with shapes (2,3) (3,3) 
Cannot add shapes (2, 3) and (3, 3)


### Integer Overflow

Be careful with integer dtypes - they can overflow silently.

In [15]:
a = np.array([120, 130], dtype=np.int8)  # int8 max is 127
b = np.array([10, 10], dtype=np.int8)

print(f"a = {a} (dtype: {a.dtype})")
print(f"b = {b}")
print(f"a + b = {a + b}  <-- overflow!")

# Fix: use a larger dtype
a_safe = a.astype(np.int32)
b_safe = b.astype(np.int32)
print(f"\nWith int32: a + b = {a_safe + b_safe}  <-- correct")

OverflowError: Python integer 130 out of bounds for int8

## 10. Exercises

Try these on your own:

1. Create two 4x4 matrices with random integers and compute their sum and difference.
2. Given a 3x3 matrix, subtract the row-wise mean from each row using broadcasting. (Hint: use `.mean(axis=1, keepdims=True)`).
3. Verify that $k \cdot (A + B) = k \cdot A + k \cdot B$ for a scalar $k$ and two 2x2 matrices.

In [ ]:
# Your code here
