# Matrix Multiplication with NumPy

This tutorial covers the fundamentals of matrix multiplication using NumPy. You'll learn how to create matrices, perform various types of multiplication, and understand the rules and properties behind them.

## 1. Setup

First, let's import NumPy.

In [1]:
import numpy as np

## 2. Creating Matrices

In NumPy, matrices are represented as 2D arrays. Let's create a few matrices to work with.

In [2]:
# A 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# A 3x2 matrix
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("Matrix A (2x3):")
print(A)
print(f"Shape: {A.shape}\n")

print("Matrix B (3x2):")
print(B)
print(f"Shape: {B.shape}")

Matrix A (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Matrix B (3x2):
[[ 7  8]
 [ 9 10]
 [11 12]]
Shape: (3, 2)


## 3. Matrix Multiplication Basics

For matrix multiplication to be valid, the number of **columns** in the first matrix must equal the number of **rows** in the second matrix.

If $A$ is an $(m \times n)$ matrix and $B$ is an $(n \times p)$ matrix, the result $C = A \cdot B$ is an $(m \times p)$ matrix where:

$$C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}$$

NumPy provides multiple ways to perform matrix multiplication:

In [3]:
# Method 1: np.matmul()
C1 = np.matmul(A, B)

# Method 2: the @ operator (recommended, equivalent to np.matmul)
C2 = A @ B

# Method 3: np.dot() - behaves the same as matmul for 2D arrays
C3 = np.dot(A, B)

print("A @ B =")
print(C1)
print(f"Result shape: {C1.shape}\n")

# Verify all three methods give the same result
print("All methods equal:", np.array_equal(C1, C2) and np.array_equal(C2, C3))

A @ B =
[[ 58  64]
 [139 154]]
Result shape: (2, 2)

All methods equal: True


### Manual Verification

Let's verify the result by computing one element by hand. The element at row 0, column 0 of the result is:

$$C_{00} = A_{00} \cdot B_{00} + A_{01} \cdot B_{10} + A_{02} \cdot B_{20}$$

In [4]:
c_00 = A[0, 0] * B[0, 0] + A[0, 1] * B[1, 0] + A[0, 2] * B[2, 0]
print(f"Manual C[0,0]: {A[0,0]}*{B[0,0]} + {A[0,1]}*{B[1,0]} + {A[0,2]}*{B[2,0]} = {c_00}")
print(f"NumPy  C[0,0]: {C1[0, 0]}")
print(f"Match: {c_00 == C1[0, 0]}")

Manual C[0,0]: 1*7 + 2*9 + 3*11 = 58
NumPy  C[0,0]: 58
Match: True


## 4. Element-wise vs. Matrix Multiplication

A common source of confusion: the `*` operator performs **element-wise** multiplication (Hadamard product), not matrix multiplication. Element-wise multiplication requires both matrices to have the same shape.

In [5]:
X = np.array([[1, 2],
              [3, 4]])

Y = np.array([[5, 6],
              [7, 8]])

print("Element-wise multiplication (X * Y):")
print(X * Y)

print("\nMatrix multiplication (X @ Y):")
print(X @ Y)

Element-wise multiplication (X * Y):
[[ 5 12]
 [21 32]]

Matrix multiplication (X @ Y):
[[19 22]
 [43 50]]


## 5. Properties of Matrix Multiplication

### 5.1 Non-Commutativity

Matrix multiplication is **not** commutative in general: $A \cdot B \neq B \cdot A$.

In [6]:
print("X @ Y =")
print(X @ Y)

print("\nY @ X =")
print(Y @ X)

print(f"\nX @ Y == Y @ X? {np.array_equal(X @ Y, Y @ X)}")

X @ Y =
[[19 22]
 [43 50]]

Y @ X =
[[23 34]
 [31 46]]

X @ Y == Y @ X? False


### 5.2 Associativity

Matrix multiplication **is** associative: $(A \cdot B) \cdot C = A \cdot (B \cdot C)$.

In [7]:
P = np.array([[1, 2], [3, 4]])
Q = np.array([[5, 6], [7, 8]])
R = np.array([[9, 10], [11, 12]])

left = (P @ Q) @ R
right = P @ (Q @ R)

print("(P @ Q) @ R =")
print(left)

print("\nP @ (Q @ R) =")
print(right)

print(f"\nAssociative? {np.array_equal(left, right)}")

(P @ Q) @ R =
[[ 413  454]
 [ 937 1030]]

P @ (Q @ R) =
[[ 413  454]
 [ 937 1030]]

Associative? True


### 5.3 Distributivity

Matrix multiplication distributes over addition: $A \cdot (B + C) = A \cdot B + A \cdot C$.

In [8]:
left = P @ (Q + R)
right = P @ Q + P @ R

print("P @ (Q + R) =")
print(left)

print("\nP @ Q + P @ R =")
print(right)

print(f"\nDistributive? {np.array_equal(left, right)}")

P @ (Q + R) =
[[ 50  56]
 [114 128]]

P @ Q + P @ R =
[[ 50  56]
 [114 128]]

Distributive? True


### 5.4 Identity Matrix

The identity matrix $I$ acts as the multiplicative identity: $A \cdot I = I \cdot A = A$.

In [9]:
I = np.eye(2)
print("Identity matrix:")
print(I)

print("\nX @ I =")
print(X @ I)

print(f"\nX @ I == X? {np.array_equal(X @ I, X)}")

Identity matrix:
[[1. 0.]
 [0. 1.]]

X @ I =
[[1. 2.]
 [3. 4.]]

X @ I == X? True


### 5.5 Transpose of a Product

The transpose of a product reverses the order: $(A \cdot B)^T = B^T \cdot A^T$.

In [10]:
left = (X @ Y).T
right = Y.T @ X.T

print("(X @ Y)^T =")
print(left)

print("\nY^T @ X^T =")
print(right)

print(f"\nEqual? {np.array_equal(left, right)}")

(X @ Y)^T =
[[19 43]
 [22 50]]

Y^T @ X^T =
[[19 43]
 [22 50]]

Equal? True


## 6. Scalar Multiplication

Multiplying a matrix by a scalar scales every element.

In [11]:
scalar = 3
print(f"{scalar} * X =")
print(scalar * X)

3 * X =
[[ 3  6]
 [ 9 12]]


## 7. Matrix-Vector Multiplication

Matrix-vector multiplication is a special case where the second operand is a column vector. This is the foundation of linear transformations.

In [12]:
M = np.array([[2, 0],
              [0, 3]])

v = np.array([1, 1])

result = M @ v

print(f"Matrix M:\n{M}")
print(f"\nVector v: {v}")
print(f"\nM @ v = {result}")
print("\nThis scaling matrix stretches x by 2 and y by 3.")

Matrix M:
[[2 0]
 [0 3]]

Vector v: [1 1]

M @ v = [2 3]

This scaling matrix stretches x by 2 and y by 3.


## 8. Batch Matrix Multiplication

NumPy supports multiplying stacks (batches) of matrices. This is useful in machine learning and data processing.

In [13]:
# A batch of 3 matrices, each 2x3
batch_A = np.random.randint(0, 5, size=(3, 2, 3))

# A batch of 3 matrices, each 3x2
batch_B = np.random.randint(0, 5, size=(3, 3, 2))

# Multiply corresponding pairs
batch_C = batch_A @ batch_B

print(f"Batch A shape: {batch_A.shape}")
print(f"Batch B shape: {batch_B.shape}")
print(f"Batch C shape: {batch_C.shape}")

# Verify: batch_C[i] == batch_A[i] @ batch_B[i]
for i in range(3):
    assert np.array_equal(batch_C[i], batch_A[i] @ batch_B[i])
print("\nAll batch results verified!")

Batch A shape: (3, 2, 3)
Batch B shape: (3, 3, 2)
Batch C shape: (3, 2, 2)

All batch results verified!


## 9. Common Pitfalls

### Shape Mismatch

If the inner dimensions don't match, you'll get a `ValueError`.

In [14]:
A_bad = np.array([[1, 2, 3],
                  [4, 5, 6]])   # shape (2, 3)

B_bad = np.array([[1, 2],
                  [3, 4]])       # shape (2, 2)

try:
    result = A_bad @ B_bad
except ValueError as e:
    print(f"Error: {e}")
    print(f"Cannot multiply shapes {A_bad.shape} and {B_bad.shape}")
    print("The number of columns in A (3) must equal the number of rows in B (2).")

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
Cannot multiply shapes (2, 3) and (2, 2)
The number of columns in A (3) must equal the number of rows in B (2).


### Using `*` Instead of `@`

Remember: `*` is element-wise, `@` is matrix multiplication. They give different results!

In [15]:
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])

print("M1 * M2 (element-wise):")
print(M1 * M2)

print("\nM1 @ M2 (matrix multiplication):")
print(M1 @ M2)

print(f"\nSame result? {np.array_equal(M1 * M2, M1 @ M2)}")

M1 * M2 (element-wise):
[[ 5 12]
 [21 32]]

M1 @ M2 (matrix multiplication):
[[19 22]
 [43 50]]

Same result? False


## 10. Exercises

Try these on your own:

1. Create a 3x3 rotation matrix for a 90-degree rotation and apply it to the vector `[1, 0, 0]`.
2. Verify that $(A \cdot B)^{-1} = B^{-1} \cdot A^{-1}$ for two invertible 3x3 matrices. (Hint: use `np.linalg.inv()`).
3. Multiply a 4x3 matrix by a 3x5 matrix. What shape is the result?

In [16]:
# Your code here
